apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-access-keys
data:
  MINIO_ACCESS_KEY: TVczMmgzZ2Q2SHZqQkVnVFJ4
  MINIO_SECRET_KEY: dDZOZ1FXVWNFeUcyQXphRENWa042c2JXY3ZEQ1ZrTjZzR2laNw==
