apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
spec:
  tls:
    - hosts:
        - minio.example.com
      secretName: minio.example.com-tls
  rules:
    - host: minio.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
