apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../stack
configMapGenerator:
  - name: values
    envs:
      - values.env
patches:
  - path: cert-patch.yaml
    target:
      kind: Ingress
replacements:
  - path: dashboard-host.yaml
  - path: minio-host.yaml
  - path: director-host.yaml

  - source: { kind: ConfigMap, name: values, fieldPath: data.DASHBOARD_URL }
    targets:
      - select: { kind: ConfigMap, name: director }
        fieldPaths: [data.DASHBOARD_URL]

  - source: { kind: ConfigMap, name: values, fieldPath: data.MINIO_URL }
    targets:
      - select: { kind: ConfigMap, name: director }
        fieldPaths: [data.MINIO_URL]
