apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cyp
resources:
  - ../full-stack
patchesStrategicMerge: 
- ingress-class.yaml
patches:
- path: dashboard-patch.yaml
  target:
    kind: Ingress
    name: dashboard
- path: minio-patch.yaml
  target:
    kind: Ingress
    name: minio
