apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../full-stack/minio
patches:
- path: minio-patch.yaml
  target:
    kind: Ingress
    name: minio
- path: minio-dashboard-patch.yaml
  target:
    kind: Ingress
    name: minio-dashboard
